p_save_path = ':s/'
classes = ('__background__', # always index 0
			 'aeroplane', 'bicycle', 'bird', 'boat',
			 'bottle', 'bus', 'car', 'cat', 'chair',
			 'cow', 'diningtable', 'dog', 'horse',
			 'motorbike', 'person', 'pottedplant',
			 'sheep', 'sofa', 'train', 'tvmonitor')

#'aeroplane', 'boat',  'bottle', 'bus', 'car', 


# not sure: 'diningtable', 'person', 'pottedplant', 'sofa', 'train', 'tvmonitor'


# 'bicycle', 'bird',  'cat', 'chair', 'cow', 'dog', 'horse', 'motorbike',  ,'sheep'

voc_physical_class_ids = [6, 7] 
physical_class_ids = [3, 6, 7, 8, 11, 12, 25,
29, 60, 69, 70, 71, 73] 
# car, bus, train, truck, fire hydrant, stop sign, backpack
# suitcase, bed, microwave, oven, toaster, refrigerator,
cls_valid_list = {0,1,3,12,16,20,21,23,24,46,57,61}
coco_classes = ('__background__', # always index 0
			 'person', 'bicycle', 'car','motorbike',
'aeroplane',
'bus',
'train',
'truck',
'boat',
'traffic light',
'fire hydrant',
'stop sign',
'parking meter',
'bench',
'bird',
'cat',
'dog',
'horse',
'sheep',
'cow',
'elephant',
'bear',
'zebra',
'giraffe',
'backpack',
'umbrella',
'handbag',
'tie',
'suitcase',
'frisbee',
'skis',
'snowboard',
'sports ball',
'kite',
'baseball bat',
'baseball glove',
'skateboard',
'surfboard',
'tennis racket',
'bottle',
'wine glass',
'cup',
'fork',
'knife',
'spoon',
'bowl',
'banana',
'apple',
'sandwich',
'orange',
'broccoli',
'carrot',
'hot dog',
'pizza',
'donut',
'cake',
'chair',
'sofa',
'pottedplant',
'bed',
'diningtable',
'toilet',
'tvmonitor',
'laptop',
'mouse',
'remote',
'keyboard',
'cell phone',
'microwave',
'oven',
'toaster',
'sink',
'refrigerator',
'book',
'clock',
'vase',
'scissors',
'teddy bear',
'hair drier',
'toothbrush')